package com.lt.vu.softwaredevelopment.mybatis;

import javax.enterprise.inject.Model;

public class Group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUPS.ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUPS.NAME
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GROUPS.PROJECT_ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    private Long projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUPS.ID
     *
     * @return the value of PUBLIC.GROUPS.ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUPS.ID
     *
     * @param id the value for PUBLIC.GROUPS.ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUPS.NAME
     *
     * @return the value of PUBLIC.GROUPS.NAME
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUPS.NAME
     *
     * @param name the value for PUBLIC.GROUPS.NAME
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GROUPS.PROJECT_ID
     *
     * @return the value of PUBLIC.GROUPS.PROJECT_ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GROUPS.PROJECT_ID
     *
     * @param projectId the value for PUBLIC.GROUPS.PROJECT_ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }
}
