package com.lt.vu.softwaredevelopment.mybatis;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.TITLE
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.ID
     *
     * @return the value of PUBLIC.PROJECT.ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.ID
     *
     * @param id the value for PUBLIC.PROJECT.ID
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.TITLE
     *
     * @return the value of PUBLIC.PROJECT.TITLE
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.TITLE
     *
     * @param title the value for PUBLIC.PROJECT.TITLE
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}
