package com.lt.vu.softwaredevelopment.mybatis.dao;

import com.lt.vu.softwaredevelopment.mybatis.Group;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    Group selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    List<Group> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GROUPS
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    int updateByPrimaryKey(Group record);
}
