package com.lt.vu.softwaredevelopment.mybatis.dao;

import com.lt.vu.softwaredevelopment.mybatis.Project;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    Project selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Wed Apr 20 13:55:16 EEST 2022
     */
    int updateByPrimaryKey(Project record);
}
